### ISSUE TITLE
there are duplicate request in the har file

### ISSUE THREAD

**Issue by zhiy** [webmetrics/browsermob-proxy#120] opened 2013-07-27 08:48 UTC
when I use it to capture traffic, there are duplicated requests in har file.

e.g. there are 2 favicon.ico requests, and also there are duplicated request for other resources?

Why is that?

**Comment by lightbody** [comment] 2013-07-27 22:26
Closing this ticket out. I'm not tracking this project much anymore since I have forked it off at http://github.com/lightbody/browsermob-proxy. I would normally suggest you open issues there, but in this case I will need a _LOT_ more info before I can assist. To start with: a reproducible test case. I suggest posting to the mailing list is the best place to start.

**Closed as completed by lightbody** 2013-07-27 22:26 UTC
